ruyisdk/llvm-project

clang/include/clang/Sema/Sema.h
clang/lib/Parse/ParsePragma.cpp
clang/lib/Sema/SemaLookup.cpp
clang/test/Driver/riscv-arch.c
clang/test/Preprocessor/riscv-target-features.c
clang/test/Sema/riscv-bad-intrinsic-pragma.c
llvm/lib/Support/RISCVISAInfo.cpp

This PR is the first step towards rvv 0.7.1, including:
- Added a new pragma for rvv 0.7.1 as  `#pragma clang riscv intrinsic vector0p7`
- Added support for specifying vector extension version in `-march` as `v0p7` (instead of `v` which stands for rvv 1.0)
- Clang now tells cc1 `-target-feature +v0p7` instead of `+v`, (though this is unnecessary at the moment, but it may help the assembler to choose the correct binary encoding).
- Updated unit tests
Future work:
- TableGen for something like `riscv_vector0p7.td`, much like the approach here: https://reviews.llvm.org/D148308

[RVV 0.7.1] Add pragma about rvv 0.7.1

---

llvm/lib/Support/RISCVISAInfo.cpp
llvm/unittests/Support/RISCVISAInfoTest.cpp

Discovered during porting rvv0.7.1 assembler tests from binutils

[RVV 0.7.1] reject when both `v` and `xtheadv` are specified

---

llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/add.s
llvm/test/MC/RISCV/rvv0p71/macc.s
llvm/test/MC/RISCV/rvv0p71/sub.s
llvm/test/MC/RISCV/rvv0p71/vector-insns.s

This PR adapted rvv 0.7.1 assembler tests from [binutils-gdb](https://github.com/riscvarchive/riscv-binutils-gdb/blob/rvv-0.7.1/gas/testsuite/gas/riscv/vector-insns.d).
Running the test reveals that `Vamo` instructions, some pseudo-instructions, and macros are not implemented, which will be addressed in future PRs.

[RVV 0.7.1] port assembler tests from binutils

---

llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/vector-insns.s

This PR added pseudo-instructions for `vmsg{t,e}{u}.vv  vd, va, vb, vm`

[RVV 0.7.1] add vector integer compare pseudos, the vv case

---

llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/invalid.s

Discovered by randomly fuzzing instructions from `llvm/test/MC/RISCV/rvv`

[RVV 0.7.1] ensure `vmsge{u}.vx` does not use the same register for emporary and destination

---

llvm/lib/Target/RISCV/AsmParser/RISCVAsmParser.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/vector-insns.s

Now all vector integer compare pseudo-instructions should be supported.

[RVV 0.7.1] add vector integer compare, the vi case

---

llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/vector-insns.s

In these two commits vamo instructions and corresponding tests are added.
Will add intrinsics for vamo instructions in following commits.

Add vamo instructions.

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vamoadd.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoand.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomax.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomaxu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomin.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamominu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoor.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoswap.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoxor.ll

This PR contains support for intrinsics of vamo instructions. Here's an overview of this PR:
- Name of classes representing vamo instructions (namely, XVAMO classes in RISCVInstrInfoXTHeadV.td) are updated to get a consistent naming style with other classes in that file, and to make life easier when writing pseudos.
- Define intrinsics, pats and pseudos.
- Finally, test all these intrinsics. The tests are generated by the script [here](https://gist.github.com/AinsleySnow/3ca1445de334669794f8bfadee280bc5).

[LLVM] [RVV 0.7.1] Add vamo intrinsics.

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVFeatures.td
llvm/lib/Target/RISCV/RISCVInstrInfoVPseudos.td
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vsetvl.ll
llvm/test/CodeGen/RISCV/rvv0p71/vsetvlmax.ll

Thie PR is cherry-picked from #14 to simplify review.
- Fixed the bug that the LLVM intrinsic `xvsetvl` is not overloaded. Discovered in #14 
- Added TableGen predicate `HasStdVOrXTHeadV` to reuse similar or identical instructions from 1.0
- Updated tests

[LLVM][RVV 0.7.1] Make intrinsics overloaded and try to reuse some intrinsics from the 1.0 version

---

clang/include/clang/Basic/BuiltinsRISCVVector.def
clang/include/clang/Basic/CMakeLists.txt
clang/include/clang/Basic/riscv_vector_xtheadv.td
clang/include/clang/Sema/RISCVIntrinsicManager.h
clang/include/clang/Sema/Sema.h
clang/lib/Basic/Targets/RISCV.cpp
clang/lib/CodeGen/CGBuiltin.cpp
clang/lib/Headers/CMakeLists.txt
clang/lib/Parse/ParsePragma.cpp
clang/lib/Sema/SemaChecking.cpp
clang/lib/Sema/SemaLookup.cpp
clang/lib/Sema/SemaRISCVVectorLookup.cpp
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-error.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-intrinsic-datatypes.cpp
clang/test/Sema/riscv-bad-intrinsic-pragma.c
clang/utils/TableGen/RISCVVEmitter.cpp
clang/utils/TableGen/TableGen.cpp
clang/utils/TableGen/TableGenBackends.h

This PR should be merged after #17.
- Added TableGen file `riscv_vector_xtheadv.td`, and registered its output artifacts to the clang codebase.
- Supported the Type System in RVV C Intrinsic.
- Supported the initial clang builtin function `__builtin_rvv_xvsetvl` and `__builtin_rvv_xvsetvlmax`.
- Added `__riscv_vsetvl` and `__riscv_vsetvlmax` macro families to make the xtheadv extension compatible with the upstream 1.0 implementation.
- Added corresponding tests.
Future work:
- Try to eliminate the need of `#include <riscv_vector_xtheadv.h>`, instead, use `#include <riscv_vector.h>` everywhere for any RVV implementation.
- Generate tests from [here](https://github.com/riscv-non-isa/rvv-intrinsic-doc/tree/main/auto-generated).

[Clang][RVV 0.7.1] add some intrinsics to figure out how it worked

---

clang/include/clang/Basic/DiagnosticSemaKinds.td
clang/include/clang/Basic/riscv_vector_xtheadv.td
clang/include/clang/Sema/Sema.h
clang/lib/Sema/SemaChecking.cpp
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-error.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-errors.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-intrinsic-datatypes.cpp
clang/utils/TableGen/RISCVVEmitter.cpp

This PR:
- Added missing semantic checking for `vsetvl` builtin functions in Clang.
- Made `riscv_vector.h` forward to `riscv_vector_xtheadv.h` when the macro `__riscv_vector_xtheadv` is defined. This enables source-level compatibility between programs using different RVV versions. See the test file [rvv-errors.c](https://github.com/imkiva/llvm-project/blob/5684b9ca3b2510d912613af10be0a6c6623bee3c/clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-errors.c) for example.

[Clang][RVV 0.7.1] Source-level compatibility with RVV 1.0 in `riscv_vector.h`

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.h
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vl.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vs.ll

This PR implements unit-strided load/store intrinsics and should be merged after #21 .
- The intrinsic standard can be found [here](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1836682/1638774209491/Xuantie+900+Series+RVV-0.7.1+Intrinsic+Manual.pdf) and unit-strided intrinsic can be found in page 42.
- Define intrinsic functions and pseudo nodes for intrinsic functions in the two TableGen files. I define intrinsic for vl{b, h, w} separately (similar for vs{b, h, w}) because otherwise we cannot tell which of the three instructions the user actually wants when lowering pseudos.
- While it is possible to define intrinsic name for vle like vle{8, 16, 32, 64}, I only defined "int_riscv_xvle" here and the eew can be inferred from parameter type. This avoids writing too many tags …

[LLVM] [RVV 0.7.1] Implement RVV 0.7.1 unit-strided load/store intrinsics.

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.h
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vls.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlsu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vss.ll

Similar to #22, in the first two commits I defined pseudo and intrinsics in TableGen files and in the third and the fourth commits I added custom selecting routine and set load/store information, respectively.

[LLVM] [RVV 0.7.1] Implement RVV 0.7.1 strided load/store intrinsics.

---

llvm/lib/Target/RISCV/RISCVExpandPseudoInsts.cpp
llvm/lib/Target/RISCV/RISCVFeatures.td
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/lib/Target/RISCV/RISCVSubtarget.h
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-16.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-32.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-64.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-8.ll

This PR emulated vector register whole load/store instructions for RVV 0.7.1. After merging this PR, related code generation should work as expected: [Demo here](https://github.com/ruyisdk/llvm-project/pull/23#issuecomment-1816095955). This may also fix the vamo tests.
- `XVLE_V` and `XVSE_V` only return or accept `VR` register group, but for cases where LMUL is 2, 4, and 8, they should also return/accept `VRM2`, `VRM4` and `VRM8`. This will be addressed in future PRs.

[LLVM][RVV 0.7.1] Emulate vector register whole load/store, and fix potential instruction selection bugs

---

llvm/lib/Target/RISCV/RISCVFeatures.td
llvm/lib/Target/RISCV/RISCVSubtarget.h
llvm/test/CodeGen/RISCV/rvv0p71/vl.ll
llvm/test/CodeGen/RISCV/rvv0p71/vls.ll
llvm/test/CodeGen/RISCV/rvv0p71/vs.ll
llvm/test/CodeGen/RISCV/rvv0p71/vss.ll

In RVV 0.7.1 intrinsic we have things like this:
The corresponding LLVM intrinsic is like:
```LLVM IR
declare <vscale x 4 x half> @llvm.riscv.xvle.nxv4f16.nxv4f16(
<vscale x 4 x half>,
<vscale x 4 x half>*,
i64);
declare <vscale x 2 x float> @llvm.riscv.xvle.nxv2f32.nxv2f32(
<vscale x 2 x float>,
<vscale x 2 x float>*,
i64);
declare <vscale x 1 x double> @llvm.riscv.xvle.nxv1f64.nxv1f64(
<vscale x 1 x double>,
<vscale x 1 x double>*,
i64);
```
Currently if we directly define these intrinsic LLVM would crash because it thinks the xtheadv extension does not support this. So I modified the `hasVInstructionsF` methods to fix the crash.
This PR does fix the crash, but it is conflicted with #23 (namely, [here](https://github.com/ruyisdk/llvm-project/pull/23/commits/9cdd6061f6373e7a8b0192e90b381b …

[LLVM] [RVV 0.7.1] Enable vector with float-point element type in RVV 0.7.1.

---

llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td

Follow up of #23, when `isConvertibleToVMV_V_V` returns `false`, we still have to emulate such `vmv<1/2/4/8>r.`.
From RVV Spec 1.0:
```
vmv<nr>r.v vd,  vs2  # General form
vmv1r.v    v1,  v2   # Copy v1=v2
vmv2r.v    v10, v12  # Copy v10=v12; v11=v13
vmv4r.v    v4,  v8   # Copy v4=v8; v5=v9; v6=v10; v7=v11
vmv8r.v    v0,  v8   # Copy v0=v8; v1=v9; ...; v7=v15
```
This PR expands these `vmv<n>r.v` to a sequence of `vmv.v.v` instructions accordingly.

[LLVM][RVV 0.7.1] Emulate whole vector register move instructions

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.h
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vlx-64.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlx.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlxu-64.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlxu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vsx-64.ll
llvm/test/CodeGen/RISCV/rvv0p71/vsx.ll

This PR implements indexed load/store intrinsics described in the page 72 [here](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1836682/1638774209491/Xuantie+900+Series+RVV-0.7.1+Intrinsic+Manual.pdf).
Unlike RVV 1.0, in the RVV 0.7.1 function list, the type of indexed vector is always the same as that of the return type, so I did not define a separate search table for indexed intrinsics.
Because 32-bit platforms cannot use 64-bit indexed values, I placed tests for intrinsics taking 64-bit vectors as arguments into separate files.

[LLVM] [RVV 0.7.1] Implement RVV 0.7.1 indexed load/store intrinsics.

---

llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-16.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-32.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-64.ll
llvm/test/CodeGen/RISCV/rvv0p71/whole-load-store-8.ll

Fixes https://github.com/ruyisdk/llvm-project/pull/23#issuecomment-1816071060 :
> Found a new problem. Would be fixed in new PRs.
> 
> Our `XVLE_V` and `XVSE_V` only return or accept registers from the `VR` group, which works fine when LMUL is 1. But for LMUL cases 2, 4, and 8, these instructions should also accept `VRM2`, `VRM4`, and `VRM8`.
> 
> To illustrate, add the following test code:
> 
> ```llvm
> declare <vscale x 16 x i8> @llvm.riscv.xvadd.nxv16i8.nxv16i8(
>   <vscale x 16 x i8>,
>   <vscale x 16 x i8>,
>   <vscale x 16 x i8>,
>   iXLen);
> 
> define void @vadd_vint8m2(<vscale x 16 x i8> *%pc, <vscale x 16 x i8> *%pa, <vscale x 16 x i8> *%pb, iXLen %vl) nounwind {
> ; CHECK-LABEL: vadd_vint8m2:
> ; CHECK:       # %bb.0:
> ; CHECK-NEXT:    csrr	a4, vl
> ; CHECK-NEXT:    csrr	a5, …
```

[LLVM][RVV 0.7.1] Support whole load/store with LMUL = 2, 4, 8

---

llvm/include/llvm/IR/IntrinsicsRISCVXTHeadV.td
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.cpp
llvm/lib/Target/RISCV/RISCVISelDAGToDAG.h
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoVPseudos.td
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vleff.ll

This PR implements intrinsic for the vleff instruction. It has many conflicts with #30 and should be merged after it.
I didn't implement intrinsic for instructions other than vleff, like vlbff, vlhff, etc., because the [intrinsic document](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/resource/1836682/1638774209491/Xuantie+900+Series+RVV-0.7.1+Intrinsic+Manual.pdf) does not mention them. I will add them if they turned out to be necessary.

[LLVM][RVV 0.7.1] Implement intrinsic function for fault-only-first loads.

---

clang/test/Preprocessor/riscv-target-features.c
llvm/lib/Support/RISCVISAInfo.cpp
llvm/lib/Target/RISCV/RISCVFeatures.td
llvm/lib/Target/RISCV/RISCVISelLowering.cpp
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadVPseudos.td
llvm/test/CodeGen/RISCV/rvv0p71/vamoadd.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoand.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomax.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomaxu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamomin.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamominu.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoor.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoswap.ll
llvm/test/CodeGen/RISCV/rvv0p71/vamoxor.ll
llvm/test/MC/RISCV/attribute-arch.s
llvm/test/MC/RISCV/rvv0p71/vector-insns.s
llvm/test/MC/RISCV/rvv0p71/zvlsseg.s

Follow-up of #30, see [`the original comment (#30)`](https://github.com/ruyisdk/llvm-project/pull/30#issuecomment-1835742328)
> I just got the facts from T-Head that a separate specification is provided for `Xtheadvector`: [xtheadvector.adoc](https://github.com/T-head-Semi/thead-extension-spec/blob/master/xtheadvector.adoc)
> 
> Seems we also need the following changes:
> 
> > Extension version: 1.0.
> 
> We still coded the version in this repo as `v0.7.1`.
> 
> > * The extension `Zvamo` is renamed to `XTheadZvamo`.
> > * The extension Zvlsseg (chapter 7.8) is not a subextension but a mandatory part of XTheadVector.
> > * The `Chapter 19. Divided Element Extension ('Zvediv')` is not part of XTheadVector.
> 
> We now have `xtheadvamo`, `xtheadvlsseg`, `xtheadvediv`. Some of them should be …

[LLVM][XTHeadVector] Rearrange extensions related to xtheadvector

---

clang/include/clang/Basic/riscv_vector.td
clang/include/clang/Basic/riscv_vector_common.td
clang/include/clang/Basic/riscv_vector_xtheadv.td
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/rvv-example-memcpy.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vle16.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vle32.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vle64.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vle8.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vse16.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vse32.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vse64.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vse8.c

The goal of this PR is to make the following function work:
```c
#include <riscv_vector.h>
#include <stdint.h>
#include <stdio.h>
void memcpy_v(uint8_t *dst, const uint8_t *src, size_t n) {
for (size_t vl; n > 0; n -= vl, src += vl, dst += vl) {
vl = __riscv_vsetvl_e8m4(n);
vuint8m4_t vec_src = __riscv_th_vle8_v_u8m4(src, vl);
__riscv_th_vse8_v_u8m4(dst, vec_src, vl);
}
}
```

[Clang][XTHeadVector] Define vector unit-stride load/store intrinsics for clang

---

clang/include/clang/Basic/riscv_vector_xtheadv.td
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlb.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlbu.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlh.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlhu.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlw.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vlwu.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vsb.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vsh.c
clang/test/CodeGen/RISCV/rvv0p71-intrinsics-handcrafted/vsw.c

[Clang][XTHeadVector] Add missing unit-stride load/store for `b/h/w` in clang

---

llvm/lib/Target/RISCV/RISCVInstrInfo.cpp
llvm/test/CodeGen/RISCV/rvv0p71/vadd.ll
llvm/test/CodeGen/RISCV/rvv0p71/vleff.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlsegeff.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlssegb.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlssege.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlssegh.ll
llvm/test/CodeGen/RISCV/rvv0p71/vlssegw.ll

Found a bug during writing intrinsic for `vlxseg`. Originally the `needVSETVLIForCOPY` method only checks COPY nodes with physical register sources. However for those nodes that have virtual register source and physical register destination and are to be converted to `PseudoTH_VMV_V_V` , this approach misses to generate `csrrs` + `vsetvli` for them.
This PR fixes the problem and updates tests. This introduces even more redundant instructions, but the behavior of the program is correct.

[LLVM][XTHeadVector] Check if either operands of a COPY node is a physical one in `needVSETVLIForCOPY`.

---

llvm/lib/Target/RISCV/RISCVInstrInfoXTHeadV.td
llvm/test/MC/RISCV/rvv0p71/xtheadvector-pseudos.s

> Beyond the instructions and pseudo instructions in the referenced specification,
> the following additional pseudo instructions are defined in order to improve compatibility with RVV 1.0:
> ```
>    th.vmmv.m vd,v          => th.vmand.mm vd,vs,vs
>    th.vneg.v vd,vs         => th.vrsub.vx vd,vs,x0
>    th.vncvt.x.x.v vd,vs,vm => th.vnsrl.vx vd,vs,x0,VM
>    th.vfneg.v vd,vs        => th.vfsgnjn.vv vd,vs,vs
>    th.vfabs.v vd,vs        => th.vfsgnjx.vv vd,vs,vs
> ```
Reference: https://github.com/T-head-Semi/thead-extension-spec/pull/40

[LLVM][XTHeadVector] Add new pseudoinstructions from T-Head upstream
